@startuml
agent user

component Я.Диалоги {
    }
component device
component speech_api
component async_api
database elastic
component "Yandex Translate" as y_translate

async_api <--> elastic
user <--> device
device <--> Я.Диалоги
Я.Диалоги <---> speech_api
speech_api <-> y_translate: перевод имён, названий фильмов
speech_api <--> async_api
@enduml